controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      joint_1: { trajectory: 0.2, goal: 0.1 }
      joint_2: { trajectory: 0.2, goal: 0.1 }
      joint_3: { trajectory: 0.2, goal: 0.1 }
      joint_4: { trajectory: 0.2, goal: 0.1 }
      joint_5: { trajectory: 0.2, goal: 0.1 }
      joint_6: { trajectory: 0.2, goal: 0.1 }
